# path of policy file and xml file
# LEGGED_GYM_ROOT_DIR is the root directory of LeggedGym repository
policy_path: "{LEGGED_GYM_ROOT_DIR}/sim2sim_test/ckpt/tutorial_policy.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/orca_description/mjcf/orca_description_12dof.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.001
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.025; 40Hz)
control_decimation: 25

# the actuator kp and kd values for each joint
kps: [75, 50, 50, 75, 30, 5, 75, 50, 50, 75, 30, 5]
kds: [3, 3, 3, 3, 2, 1, 3, 3, 3, 3, 2, 1]

# the default angles for each joint
default_angles: [0.0,  0.0,  0.0,  0.0, 0.0, 0.0, 
                0.0,  0.0,  0.0,  0.0, 0.0, 0.0]

# the observation scales
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
cmd_scale: [2.0, 2.0, 0.25]

# the action scales
action_scale: 0.25

num_actions: 12
num_obs: 47

# the command to be sent to the robot
# cmd velocity: [saggital, lateral, yaw]
cmd_init: [0.5, 0, 0]